# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'config_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_ConfigDialog(object):
    def setupUi(self, ConfigDialog):
        ConfigDialog.setObjectName("ConfigDialog")
        ConfigDialog.setWindowModality(QtCore.Qt.ApplicationModal)
        ConfigDialog.resize(400, 300)
        self.formLayout = QtWidgets.QFormLayout(ConfigDialog)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(ConfigDialog)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.SpanningRole, self.label)
        self.line = QtWidgets.QFrame(ConfigDialog)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.SpanningRole, self.line)
        self.pinLabel = QtWidgets.QLabel(ConfigDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pinLabel.sizePolicy().hasHeightForWidth())
        self.pinLabel.setSizePolicy(sizePolicy)
        self.pinLabel.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.pinLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.pinLabel.setObjectName("pinLabel")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.pinLabel)
        self.pinSelector = QtWidgets.QComboBox(ConfigDialog)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pinSelector.sizePolicy().hasHeightForWidth())
        self.pinSelector.setSizePolicy(sizePolicy)
        self.pinSelector.setObjectName("pinSelector")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.pinSelector)
        self.label_2 = QtWidgets.QLabel(ConfigDialog)
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.SpanningRole, self.label_2)
        self.line_2 = QtWidgets.QFrame(ConfigDialog)
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.SpanningRole, self.line_2)
        self.label_3 = QtWidgets.QLabel(ConfigDialog)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.ipAddressLine = QtWidgets.QLineEdit(ConfigDialog)
        self.ipAddressLine.setInputMask("")
        self.ipAddressLine.setText("")
        self.ipAddressLine.setObjectName("ipAddressLine")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.ipAddressLine)
        self.label_4 = QtWidgets.QLabel(ConfigDialog)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.portLine = QtWidgets.QLineEdit(ConfigDialog)
        self.portLine.setObjectName("portLine")
        self.formLayout.setWidget(7, QtWidgets.QFormLayout.FieldRole, self.portLine)
        self.pingButton = QtWidgets.QPushButton(ConfigDialog)
        self.pingButton.setObjectName("pingButton")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.SpanningRole, self.pingButton)
        self.buttonBox = QtWidgets.QDialogButtonBox(ConfigDialog)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(9, QtWidgets.QFormLayout.SpanningRole, self.buttonBox)

        self.retranslateUi(ConfigDialog)
        self.buttonBox.accepted.connect(ConfigDialog.accept)
        self.buttonBox.rejected.connect(ConfigDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(ConfigDialog)

    def retranslateUi(self, ConfigDialog):
        _translate = QtCore.QCoreApplication.translate
        ConfigDialog.setWindowTitle(_translate("ConfigDialog", "Form"))
        self.label.setText(_translate("ConfigDialog", "Output"))
        self.pinLabel.setText(_translate("ConfigDialog", "Active Pin"))
        self.label_2.setText(_translate("ConfigDialog", "Server"))
        self.label_3.setText(_translate("ConfigDialog", "IP Address"))
        self.ipAddressLine.setPlaceholderText(_translate("ConfigDialog", "localhost"))
        self.label_4.setText(_translate("ConfigDialog", "Port"))
        self.portLine.setPlaceholderText(_translate("ConfigDialog", "5000"))
        self.pingButton.setText(_translate("ConfigDialog", "Ping"))

